#pragma once

#define LC_HEADER					0xF0
#define LC_MUHELPER_OFF_ACTION		0x01
#define LC_MUHELPER_OFF_START		0x02
#define LC_MUHELPER_OFF_STOP		0x03

#define LC_HUNTING_DATA				0x04
#define LC_HUNTING_SKILL			0x05
#define LC_HUNTING_EXP				0x06
#define LC_HUNTING_LEVEL_UP			0x07